config/routes.rb
Rails.application.routes.draw do
  
  get 'home/about'
  devise_for :users, :controllers => {
  	:registrations => 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]

  resources :users, only: [:show, :index, :create, :edit, :update]

  resources :root, only: [:top]
  
  root 'root#top'



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <p><big><font color="white">Bookers2</font></big></p>
        </nav>
        <nav>
         <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
          <% if user_signed_in? %>
            <li>
              <%= link_to "Home",user_path(current_user.id), class:"home" %>
            </li>
            <li class="">
              <%= link_to "Users",users_path,class:"users" %>
            </li>
            <li class="">
              <%= link_to "Books",books_path,class:"books" %>
            </li>
            <li>
              <%= link_to "Log out",destroy_user_session_path, method: :delete,class:"logout" %>
            </li>
          <% else %>
            <li class="">
              <%= link_to "Home","/",class:"home" %>
            </li>
            <li class="">
              <%= link_to "About",home_about_path, class:"about" %>
            </li>
            <li>
              <%= link_to "Sign up",new_user_registration_path,class:"sign_up" %>
            </li>
            <li>
              <%= link_to "Log in",new_user_session_path,class:"sign_in" %>
            </li>
          <% end %>
        </ul>
      </nav>
      </div>
    </header>

    <p></p><br />

    <%= yield %>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert">
        <%= flash[:alert] %>
      </div>
    <% end %>

  </body>
</html>